osx_image: xcode7.2
language: objective-c

env:
global:
- APP_NAME="MySocially"
- 'DEVELOPER_NAME="iPhone Developer: hui zeng (3ED55WY2DM)"'
- PROFILE_NAME="gino"

xcode_workspace: ZHWorkspace.xcworkspace
xcode_scheme: MySocially 

xcodebuild -workspace {workspace}.xcworkspace -scheme {scheme} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
